### ISSUE TITLE
DBIx::Class::Schema::Loader marked as both build_requires and recommends

### ISSUE THREAD

**Issue by fgabolde** [ironcamel/Dancer2-Plugin-DBIC#18]
Reading through the source code, it seems that DBIx::Class::Schema::Loader is never required; at worst it is dynamically required in tests which are skipped if DBICSL is not available.

DBICSL is still inserted into `build_requires` by dzil (maybe AutoPrereqs doesn't understand `eval { require ... }` ?) and so it is installed as a dependency. This is unfortunate since it has a pretty hefty dependency graph of its own, especially through `Lingua::*`, and most production environments don't require it since it is usually only used during development.

**Comment by ironcamel** [comment]
This plugin is a thin wrapper around DBICx::Sugar which uses D::C::S::Loader: https://metacpan.org/source/IRONCAMEL/DBICx-Sugar-0.0100/lib/DBICx/Sugar.pm#L98

**Comment by hvoers** [comment]
No. DBICx::Sugar does not use D::C::S::Loader
Please re-open this issue.

**Comment by ironcamel** [comment]
@hvoers can you clarify what you mean?  I provided a link to the line in the DBICx::Sugar source code where it in fact does use D::C::S::Loader.

**Comment by hvoers** [comment]
Sorry.
I do not use Dancer anymore.
It did not work for me.

**Comment by fgabolde** [comment]
@ironcamel I just found out I wrote the original version of the patch which enabled ::Loader to be an **optional** dependency, here: https://github.com/ironcamel/Dancer-Plugin-DBIC/pull/3 From the code structure in ::Sugar it looks like it was inherited from there (but the error message was made better than mine, thankfully). Then somebody wrote the corresponding documentation:

> If a schema_class option is not provided, then DBIx::Class::Schema::Loader will be used to dynamically load the schema by introspecting the database corresponding to the dsn value. You need DBIx::Class::Schema::Loader installed for this to work.

My use case now is still the same as it was then. My DBIC schema cannot be generated automatically by ::Loader because it contains many handwritten extra methods, some base classes have been changed, etc. I suspect it is rare for generated schemas to be used in nontrivial apps. I don't have a need for ::Loader or the classes that it pulls.

**Comment by ironcamel** [comment]
@fgabolde ok I will update the `dist.ini/Makefile.PL` to remove the hard dependency on `::Loader`, like I did for `DBICx::Sugar`.  The frustrating part is that adding `::Loader` to the `[Prereqs / RuntimeRecommends]` section of `dist.ini` makes it a hard dependency instead of an optional dependency which is what I wish would happen.
