### ISSUE TITLE
Docs specify to import specific methods

### ISSUE THREAD

**Issue by aibistin** [ironcamel/Dancer2-Plugin-DBIC#22]
Hi, 
In version 0.0013, the docs say that you can import specific methods. 
(Note: This is from the [metacpan.org](https://metacpan.org/pod/Dancer2::Plugin::DBIC) docs.)
`use Dancer2::Plugin::DBIC qw(schema resultset rset);`
I believe it should read,
`use  use Dancer2::Plugin::DBIC;`
Otherwise you will get this error: 

> "Specific subroutines cannot be exported from plugin"

Thanks,
Austin

**Comment by racke** [comment]
Yes, this is correct. `qw(schema resultset rset)` should be removed.

**Comment by racke** [comment]
Actually it has been removed in the Git repository. @ironcamel, any chance for a release?

**Comment by ironcamel** [comment]
Thanks guys. I will cut a release tonight. If I forget, feel free to keep pinging me.

**Comment by ironcamel** [comment]
I just published the latest version to CPAN.

**Comment by aibistin** [comment]
Thanks.
