### ISSUE TITLE
DEPRECATED: Dancer2::Plugin::DBIC calls

### ISSUE THREAD

**Issue by satmovi** [ironcamel/Dancer2-Plugin-DBIC#5]
Hello,
I was trying to get rid of this warning:
DEPRECATED: Dancer2::Plugin::DBIC calls 'dsl' instead of '$dsl->dsl'. at /usr/local/share/perl/5.14.2/Dancer2/Plugin/DBIC.pm line 15

I was able to find some discussions related to it:
https://github.com/PerlDancer/Dancer2/issues/418

My solution was to change the plugin to:
use Dancer2::Plugin qw(:no_dsl);

That fixed the problem, but I'm not sure about the impact on the module.
Can you please have a look?

Thanks,
Ovidiu

**Comment by fgabolde** [comment]
@ironcamel Was this reverted somehow? I don't see `:no_dsl` anywhere in DBIC.pm and I do get the warnings when I call `schema`.

**Comment by ironcamel** [comment]
Yeah, it seems like I reverted it when I refactored D::P::DBIC to use https://metacpan.org/pod/DBICx::Sugar (to get rid of code duplication between the dancer1 and dancer2 plugins). My reasoning was that the no_dsl option is no longer documented here https://metacpan.org/pod/Dancer2::Plugin, so I thought it no longer exists.

**Comment by ironcamel** [comment]
I installed Dancer2::Plugin::DBIC 0.0009 and Dancer2 0.160000 and ran the tests under t/* and I did not get that warning. Can you show a snippet of your code showing how you are using the plugin?

**Comment by fgabolde** [comment]
I think I got it. We have an app that uses the DBIC plugin directly, and a plugin that uses the DBIC plugin *and* calls functions from a module that `use`s Dancer2 and the DBIC plugin... I think `_get_dsl` got lost somewhere in the maze and thus `plugin_setting` causes the warnings. This is not specific to the DBIC plugin, methinks.

I never managed to get the issue narrowed down to a minimal working example, but here is a stack trace at least:

    [CENSURED:18069] error @2015-06-22 13:20:49> Route exception: DEPRECATED: Dancer2::Plugin::DBIC calls 'dsl' instead of '$dsl->dsl'. at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Plugin.pm line 216.
	Dancer2::Plugin::__ANON__("Dancer2::Plugin::DBIC") called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Plugin.pm line 244
	Dancer2::Plugin::_get_dsl() called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Plugin.pm line 138
	Dancer2::Plugin::plugin_setting() called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Plugin/DBIC.pm line 13
	Dancer2::Plugin::DBIC::_schema(Dancer2::Core::DSL__WITH__Dancer2::Plugin::DBIC=HASH(0x530ec68)) called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Plugin/DBIC.pm line 19
	Dancer2::Plugin::DBIC::_rset(Dancer2::Core::DSL__WITH__Dancer2::Plugin::DBIC=HASH(0x530ec68), "User") called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Core/Role/DSL.pm line 71
	Dancer2::Core::Role::DSL::__ANON__("User") called at /home/fgabolde/work/java/CENSURED/bin/../lib/CENSURED/Route/Accounts.pm line 22
	CENSURED::Route::Accounts::__ANON__(Dancer2::Core::App=HASH(0x2dfb1e0)) called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Core/Route.pm line 136
	Dancer2::Core::Route::execute(Dancer2::Core::Route=HASH(0x5208810), Dancer2::Core::App=HASH(0x2dfb1e0)) called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Core/App.pm line 1361
	eval {...} called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Core/App.pm line 1362
	Dancer2::Core::App::_dispatch_route(Dancer2::Core::App=HASH(0x2dfb1e0), Dancer2::Core::Route=HASH(0x5208810)) called at /home/fgabolde/perl5/perlbrew/perls/dataranger/lib/site_perl/5.18.2/Dancer2/Core/App.pm line 1250

I'll try to setup a MWE from scratch but this is probably an issue either in Dancer2 or (more likely) PEBKAC.  I don't think I know how to properly call a plugin from a plugin, or how to use a plugin from a regular module without making the module a D2 app...

**Comment by ironcamel** [comment]
I have used the dbic plugin inside of a script outside of a web app context by simply creating a script like this in the `./bin` dir:

```perl
use Dancer qw(:script config);
use Dancer::Plugin::DBIC qw(schema rset);
my $rset = rset(...);
```

Putting it in `./bin` makes it so Dancer knows where to look for the configs.

**Comment by fgabolde** [comment]
Yes, this used to work with D1, no longer in D2 (D2 actually looks for `:script`, `:syntax` and `:tests` and skips them over).
